### ISSUE TITLE
typings for leaflet markercluster

### ISSUE THREAD

**Issue by simonebracaloni** [Asymmetrik/angular2-leaflet-markercluster#2]
I had some issue with at-loader while building the project. I had to change 
@types/leaflet-markercluster
to 
@types/leaflet.markercluster

in the dependencies.

Hope it helps.

**Comment by reblace** [comment]
I think there was a typo in your comment, can you provide some more detail?

**Comment by reblace** [comment]
Oh yeah, sorry I hadn't had a chance to update the README yet. This component was just made a couple weeks ago. I'll fix that soon, thanks!

**Comment by reblace** [comment]
I updated the README with more usage details. Thanks for the feedback and for using the plugin!

**Comment by reblace** [comment]
Oh, hah, and I just noticed they must have just renamed the typings in DefinitelyTyped. I'm pushing out a corrected package.json now.
