### ISSUE TITLE
Clustering Polylines and Polygons

### ISSUE THREAD

**Issue by K0ntrol** [Asymmetrik/angular2-leaflet-markercluster#5]
Is it possible to extend the Polygon and Polyline classes to create clusterable shapes in similar way as with JS Leaflet (see snippet)? Just inserting the following snippet gives an unsurprising
> Property clusterableX does not exist on type 'typeof L'
```
L.ClusterablePolyline = L.Polyline.extend({
    _originalInitialize: L.Polyline.prototype.initialize,

    initialize: function (bounds, options) {
        this._originalInitialize(bounds, options);
        this._latlng = this.getBounds().getCenter();
    },

    getLatLng: function () {
        return this._latlng;
    },

    // dummy method.
    setLatLng: function () {
    }
});


L.ClusterablePolygon = L.Polygon.extend({
    _originalInitialize: L.Polygon.prototype.initialize,

    initialize: function (bounds, options) {
        this._originalInitialize(bounds, options);
        this._latlng = this.getBounds().getCenter();
    },

    getLatLng: function () {
        return this._latlng;
    },

    // dummy method.
    setLatLng: function () {
    }
});
```

**Comment by reblace** [comment]
This is a typescript error. If you want to do this, you'll need to either create typings that extend the L namespace to have ```CluterableX``` interfaces/classes or cast ```L``` to ```any``` and then do your operations:

```
let L_any = L as any;
L_any.ClusterablePolyline = L.Polyline.extend(...);
```

**Comment by K0ntrol** [comment]
Thank you for your advice!

I tried the `let L_any = L as any;`  but his just creates a new error:
>ERROR TypeError: this.callInitHooks is not a function
    at Object.NewClass [as ClusterablePolyline]

I remember coming across this error earlier when I was experimenting with pure JavaScript and I resolved it by declaring the variables earlier in source code. In Angular I have tried declaring them in ngOnInit and onMapReady but both of them produce the TypeError. I also tried to create them outside the prementioned functions but no cigar. I am out of ideas as it is.

**Comment by reblace** [comment]
If I had to guess, I'd say it has something to do with the interplay between the way that leaflet's extension works, how you're referencing 'this', and how Typescript interprets and compiles all of that.

It's probably resolving ```this``` to the scope of the ```L.ClusterableX``` definition. Which means, ```this``` is not what you expect it to be.

**Comment by reblace** [comment]
I'm gonna close this though, it isn't really an issue with the ng2 wrapper.

You can check out the @asymmetrik/leaflet-d3 project for an example of writing/publishing a leaflet plugin for consumption by a Typescript project (it includes an example d.ts file).

This would allow you to package your Clusterable Poly classes and include them in an angular project without having to write them in Typescript (which I'm not sure there's a good way to do).

Thanks for checking out this project, and hopefully this helps you!

**Comment by K0ntrol** [comment]
Just to check in that I got it working!

I declared the new variables in onMapReady function by using the following code:

```
(L as any).ClusterablePolyline = L.Polyline.extend({
      _originalInitialize: (L as any).Polyline.prototype.initialize,

      initialize: function (bounds, options?) {
        this._originalInitialize(bounds, options);
        this._latlng = this.getBounds().getCenter();
      },

      getLatLng: function () {
        return this._latlng;
      },

      // dummy method.
      setLatLng: function () {
      }
    });

    (L as any).clusterablePolyline = function (latlngs, options?) {
      return new (L as any).ClusterablePolyline(latlngs, options);
    };


    (L as any).ClusterablePolygon = L.Polygon.extend({
      _originalInitialize: (L as any).Polygon.prototype.initialize,

      initialize: function (bounds, options?) {
        this._originalInitialize(bounds, options);
        this._latlng = this.getBounds().getCenter();
      },

      getLatLng: function () {
        return this._latlng;
      },

      // dummy method.
      setLatLng: function () {
      }
    });

    (L as any).clusterablePolygon = function (latlngs, options?) {
      return new (L as any).ClusterablePolygon(latlngs, options);
    };
```

**Comment by jackdh** [comment]
Has there been any improvement on this or is @K0ntrol 's way the only way to achieve this?

Thanks!

**Comment by xigolle** [comment]
@K0ntrol also interesed if this is something that can be "supported" by the plugin or there is a elegant solution for this.

**Comment by K0ntrol** [comment]
@xigolle I did not look further into this after getting it to work with the aforementioned not-so-elegant snippet.
